modLoader="javafml"
loaderVersion="[36,)" 
license="All rights reserved"
[[mods]] 
modId="halowip" 
version="${file.jarVersion}" 
displayName="Halo WIP" 
logoFile="examplemod.png" 
credits="Mason Wells, Anthony Nelson" 
authors="Diglis, Centiv" 
description='''
This mod is WIP
'''

[[dependencies.halowip]] 
    modId="forge" 
    mandatory=true 
    versionRange="[36,)" 
    ordering="NONE"
    side="BOTH"
[[dependencies.halowip]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
